import { useState } from 'react';
import { KeyRound, X } from 'lucide-react';
import { apiChangePin } from '../lib/api';

export default function ChangePinButton({ onChanged }: { onChanged: () => void }) {
  const [open,setOpen]=useState(false); const [currentPin,setCurrent]=useState(''); const [newPin,setNew]=useState(''); const [confirm,setConfirm]=useState(''); const [message,setMessage]=useState('');
  const submit=async()=>{if(newPin!==confirm){setMessage('Xác nhận mật khẩu không khớp.');return}try{await apiChangePin(currentPin,newPin);setMessage('Đổi mật khẩu thành công. Vui lòng đăng nhập lại.');setTimeout(onChanged,800)}catch(e){setMessage(e instanceof Error?e.message:'Không đổi được mật khẩu.')}};
  return <>{<button onClick={()=>setOpen(true)} className="flex items-center gap-1 text-[11px] font-bold text-slate-500 hover:text-blue-600"><KeyRound className="w-3.5 h-3.5"/>Đổi mật khẩu</button>}{open&&<div className="fixed inset-0 z-[100] bg-slate-950/70 grid place-items-center p-4"><div className="w-full max-w-sm bg-white rounded-2xl p-5 text-slate-900 shadow-2xl"><div className="flex justify-between"><h2 className="font-black">Thay đổi mật khẩu đăng nhập</h2><button onClick={()=>setOpen(false)}><X/></button></div><div className="grid gap-3 mt-4"><input type="password" inputMode="numeric" className="border rounded-lg p-3" placeholder="Mật khẩu hiện tại" value={currentPin} onChange={e=>setCurrent(e.target.value.replace(/\D/g,''))}/><input type="password" inputMode="numeric" className="border rounded-lg p-3" placeholder="Mật khẩu mới 6–12 chữ số" value={newPin} onChange={e=>setNew(e.target.value.replace(/\D/g,''))}/><input type="password" inputMode="numeric" className="border rounded-lg p-3" placeholder="Nhập lại mật khẩu mới" value={confirm} onChange={e=>setConfirm(e.target.value.replace(/\D/g,''))}/>{message&&<p className="text-xs font-semibold text-rose-600">{message}</p>}<button onClick={submit} className="bg-blue-600 text-white rounded-lg p-3 font-bold">Xác nhận đổi mật khẩu</button></div></div></div>}</>;
}
