import { useState, type Dispatch, type SetStateAction } from 'react';
import type { Contract, Contractor, Employee, Equipment, InventoryItem, Project } from '../types';

type Tab = 'projects'|'employees'|'partners'|'contracts'|'inventory'|'equipment';
interface Props { projects:Project[];setProjects:Dispatch<SetStateAction<Project[]>>;employees:Employee[];setEmployees:Dispatch<SetStateAction<Employee[]>>;contractors:Contractor[];setContractors:Dispatch<SetStateAction<Contractor[]>>;contracts:Contract[];setContracts:Dispatch<SetStateAction<Contract[]>>;inventoryItems:InventoryItem[];setInventoryItems:Dispatch<SetStateAction<InventoryItem[]>>;equipment:Equipment[];setEquipment:Dispatch<SetStateAction<Equipment[]>> }

export default function MasterDataEditor(p:Props){
  const [tab,setTab]=useState<Tab>('employees'); const [saved,setSaved]=useState(false);
  const mark=()=>{setSaved(true);setTimeout(()=>setSaved(false),1200)};
  const tabs:Array<[Tab,string]>=[['projects','Dự án'],['employees','Nhân viên'],['partners','Đối tác'],['contracts','Hợp đồng'],['inventory','Vật tư'],['equipment','Thiết bị']];
  const field=(value:string|undefined,onChange:(v:string)=>void,placeholder:string)=><input className="w-full border border-slate-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-blue-500" value={value||''} placeholder={placeholder} onChange={e=>onChange(e.target.value)} onBlur={mark}/>;
  return <div className="space-y-4"><div className="bg-amber-50 border border-amber-200 rounded-xl p-3 text-xs text-amber-900"><b>Nguyên tắc an toàn:</b> mã hiển thị có thể thay đổi; ID nội bộ được giữ nguyên để không làm đứt hợp đồng, bảng công, kho và lịch sử kế toán.</div>{saved&&<div className="fixed right-5 bottom-5 z-50 bg-emerald-700 text-white rounded-lg px-4 py-2 text-sm font-bold">Đã lưu và chờ đồng bộ</div>}<div className="flex flex-wrap gap-2">{tabs.map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`rounded-lg px-4 py-2 text-sm font-bold ${tab===id?'bg-blue-600 text-white':'bg-white border'}`}>{label}</button>)}</div><div className="bg-white border rounded-2xl overflow-hidden"><div className="grid grid-cols-[130px_1fr_140px] gap-3 bg-slate-100 px-4 py-3 text-xs font-black uppercase text-slate-500"><div>Mã hiển thị</div><div>Tên / Tiêu đề</div><div>ID nội bộ</div></div>
  {tab==='projects'&&p.projects.map(x=><div key={x.id} className="grid grid-cols-[130px_1fr_140px] gap-3 p-3 border-t">{field(x.code,v=>p.setProjects(a=>a.map(i=>i.id===x.id?{...i,code:v}:i)),'DA-001')}{field(x.name,v=>p.setProjects(a=>a.map(i=>i.id===x.id?{...i,name:v}:i)),'Tên dự án')}<code>{x.id}</code></div>)}
  {tab==='employees'&&p.employees.map(x=><div key={x.id} className="grid grid-cols-[130px_1fr_140px] gap-3 p-3 border-t">{field(x.code,v=>p.setEmployees(a=>a.map(i=>i.id===x.id?{...i,code:v}:i)),'NV-001')}{field(x.name,v=>p.setEmployees(a=>a.map(i=>i.id===x.id?{...i,name:v}:i)),'Họ tên')}<code>{x.id}</code></div>)}
  {tab==='partners'&&p.contractors.map(x=><div key={x.id} className="grid grid-cols-[130px_1fr_140px] gap-3 p-3 border-t">{field(x.code||x.id,v=>p.setContractors(a=>a.map(i=>i.id===x.id?{...i,code:v}:i)),'DT-001')}{field(x.name,v=>p.setContractors(a=>a.map(i=>i.id===x.id?{...i,name:v}:i)),'Tên đối tác')}<code>{x.id}</code></div>)}
  {tab==='contracts'&&p.contracts.map(x=><div key={x.id} className="grid grid-cols-[130px_1fr_140px] gap-3 p-3 border-t">{field(x.contractNumber,v=>p.setContracts(a=>a.map(i=>i.id===x.id?{...i,contractNumber:v}:i)),'HĐ-001')}{field(x.title,v=>p.setContracts(a=>a.map(i=>i.id===x.id?{...i,title:v}:i)),'Tên hợp đồng')}<code>{x.id}</code></div>)}
  {tab==='inventory'&&p.inventoryItems.map(x=><div key={x.id} className="grid grid-cols-[130px_1fr_140px] gap-3 p-3 border-t">{field(x.code,v=>p.setInventoryItems(a=>a.map(i=>i.id===x.id?{...i,code:v}:i)),'VT-001')}{field(x.name,v=>p.setInventoryItems(a=>a.map(i=>i.id===x.id?{...i,name:v}:i)),'Tên vật tư')}<code>{x.id}</code></div>)}
  {tab==='equipment'&&p.equipment.map(x=><div key={x.id} className="grid grid-cols-[130px_1fr_140px] gap-3 p-3 border-t">{field(x.code,v=>p.setEquipment(a=>a.map(i=>i.id===x.id?{...i,code:v}:i)),'TB-001')}{field(x.name,v=>p.setEquipment(a=>a.map(i=>i.id===x.id?{...i,name:v}:i)),'Tên thiết bị')}<code>{x.id}</code></div>)}
  </div></div>;
}
