import { useEffect, useMemo, useState, type Dispatch, type SetStateAction } from 'react';
import { apiFetch } from '../lib/api';
import type { Employee, Project, Timesheet, UserRole } from '../types';

interface Props { role: UserRole; employees: Employee[]; projects: Project[]; timesheets: Timesheet[]; setProjects: Dispatch<SetStateAction<Project[]>> }
const today = new Date();
const currentPeriod = today.toISOString().slice(0, 7);

export default function WorkforceAdmin({ role, employees, projects, timesheets, setProjects }: Props) {
  const [users, setUsers] = useState<any[]>([]); const [requests, setRequests] = useState<any[]>([]); const [shifts, setShifts] = useState<any[]>([]); const [periods, setPeriods] = useState<any[]>([]); const [message, setMessage] = useState('');
  const [account, setAccount] = useState({ employeeId: employees[0]?.id || '', username: '', pin: '' });
  const [shift, setShift] = useState({ employeeId: employees[0]?.id || '', projectId: projects[0]?.id || '', shiftDate: today.toISOString().slice(0,10), startTime: '07:30', endTime: '17:00', shiftName: 'Ca ngày' });
  const load = async () => {
    const [requestRows, shiftRows, periodRows] = await Promise.all([apiFetch('/api/workforce/requests'), apiFetch('/api/workforce/shifts'), apiFetch('/api/workforce/payroll-periods')]);
    setRequests(requestRows); setShifts(shiftRows); setPeriods(periodRows);
    if (role === 'CEO') setUsers(await apiFetch('/api/admin/users'));
  };
  useEffect(() => { load().catch(error => setMessage(error.message)); }, []);
  const monthRows = timesheets.filter(row => row.date.startsWith(currentPeriod));
  const stats = useMemo(() => ({ present: monthRows.filter(r => r.status === 'Present').length, late: monthRows.filter(r => r.status === 'Late').length, overtime: monthRows.filter(r => r.status === 'Overtime').length, absent: monthRows.filter(r => r.status === 'Absent').length, laborCost: employees.reduce((sum,e) => sum + (e.type === 'Seasonal' ? e.baseSalary * monthRows.filter(r => r.employeeId === e.id && r.status !== 'Absent').length : e.baseSalary), 0) }), [monthRows, employees]);
  const createAccount = async () => { const emp=employees.find(e=>e.id===account.employeeId); await apiFetch('/api/admin/users',{method:'POST',body:JSON.stringify({username:account.username,pin:account.pin,employeeId:emp?.id,fullName:emp?.name,role:'Employee'})}); setMessage('Đã tạo tài khoản nhân viên.'); await load(); };
  const review = async (id:string,status:string) => { await apiFetch(`/api/workforce/requests/${id}/review`,{method:'PATCH',body:JSON.stringify({status})}); await load(); };
  const saveShift = async () => { await apiFetch('/api/workforce/shifts',{method:'POST',body:JSON.stringify(shift)}); setMessage('Đã lưu lịch phân ca.'); await load(); };
  const period = periods.find(p=>p.period===currentPeriod);
  const lockPeriod = async (attendanceLocked:boolean,payrollLocked:boolean) => { await apiFetch(`/api/workforce/payroll-periods/${currentPeriod}`,{method:'PUT',body:JSON.stringify({attendanceLocked,payrollLocked})}); await load(); };
  const fmt = (v:number) => new Intl.NumberFormat('vi-VN').format(v)+' ₫';
  return <div className="space-y-5">
    {message&&<div className="rounded-xl bg-blue-50 border border-blue-200 p-3 text-sm font-semibold text-blue-800">{message}</div>}
    <div className="grid sm:grid-cols-5 gap-3">{[['Có mặt',stats.present],['Đi muộn',stats.late],['Vắng',stats.absent],['Tăng ca',stats.overtime],['Chi phí nhân công',fmt(stats.laborCost)]].map(([k,v])=><div key={k as string} className="bg-white border rounded-xl p-4"><div className="text-xs text-slate-500">{k}</div><div className="text-xl font-black mt-1">{v}</div></div>)}</div>
    {role==='CEO'&&users.some(u=>u.role==='Employee')&&<section className="bg-white border rounded-2xl p-5"><h2 className="font-black mb-2">Xóa tài khoản nhân viên</h2><div className="flex flex-wrap gap-2">{users.filter(u=>u.role==='Employee').map(u=><button key={u.id} className="border border-rose-200 text-rose-700 rounded-lg px-3 py-2 text-xs font-bold" onClick={async()=>{if(confirm(`Xóa tài khoản ${u.username}?`)){await apiFetch(`/api/admin/users/${u.id}`,{method:'DELETE'});setMessage('Đã xóa tài khoản nhân viên.');load();}}}>Xóa {u.username}</button>)}</div></section>}
    {role==='CEO'&&<section className="bg-white border rounded-2xl p-5"><h2 className="font-black mb-4">Quản lý tài khoản nhân viên</h2><div className="grid md:grid-cols-4 gap-2"><select className="border rounded-lg p-2" value={account.employeeId} onChange={e=>setAccount({...account,employeeId:e.target.value})}>{employees.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select><input className="border rounded-lg p-2" placeholder="Tên đăng nhập" value={account.username} onChange={e=>setAccount({...account,username:e.target.value.toLowerCase()})}/><input className="border rounded-lg p-2" placeholder="Mật khẩu 6–12 số" type="password" value={account.pin} onChange={e=>setAccount({...account,pin:e.target.value.replace(/\D/g,'')})}/><button className="bg-blue-600 text-white rounded-lg font-bold" onClick={()=>createAccount().catch(e=>setMessage(e.message))}>Tạo tài khoản</button></div><div className="mt-4 overflow-x-auto"><table className="w-full text-sm"><tbody>{users.map(u=><tr key={u.id} className="border-t"><td className="p-2 font-bold">{u.username}</td><td>{u.full_name}</td><td>{u.role}</td><td><button className="text-blue-600 font-bold" onClick={async()=>{await apiFetch(`/api/admin/users/${u.id}/status`,{method:'PATCH',body:JSON.stringify({active:!u.active})});load();}}>{u.active?'Khóa':'Mở khóa'}</button></td><td><button className="text-amber-600 font-bold" onClick={async()=>{const pin=prompt('Mật khẩu mới 6–12 chữ số');if(pin){await apiFetch(`/api/admin/users/${u.id}/reset-pin`,{method:'POST',body:JSON.stringify({pin})});setMessage('Đã đặt lại mật khẩu.')}}}>Đặt lại mật khẩu</button></td></tr>)}</tbody></table></div></section>}
    <section className="grid lg:grid-cols-2 gap-5"><div className="bg-white border rounded-2xl p-5"><h2 className="font-black mb-3">Yêu cầu chờ phê duyệt</h2>{requests.filter(r=>r.status==='pending').map(r=><div key={r.id} className="border rounded-xl p-3 mb-2"><div className="font-bold">{employees.find(e=>e.id===r.employee_id)?.name||r.employee_id} • {r.request_type}</div><div className="text-xs text-slate-500">{r.reason}</div><div className="mt-2 flex gap-2"><button onClick={()=>review(r.id,'approved')} className="bg-emerald-600 text-white rounded px-3 py-1 text-xs font-bold">Duyệt</button><button onClick={()=>review(r.id,'rejected')} className="bg-rose-600 text-white rounded px-3 py-1 text-xs font-bold">Từ chối</button></div></div>)}</div><div className="bg-white border rounded-2xl p-5"><h2 className="font-black mb-3">Phân ca</h2><div className="grid gap-2"><select className="border rounded p-2" value={shift.employeeId} onChange={e=>setShift({...shift,employeeId:e.target.value})}>{employees.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select><select className="border rounded p-2" value={shift.projectId} onChange={e=>setShift({...shift,projectId:e.target.value})}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input type="date" className="border rounded p-2" value={shift.shiftDate} onChange={e=>setShift({...shift,shiftDate:e.target.value})}/><div className="flex gap-2"><input type="time" className="border rounded p-2 flex-1" value={shift.startTime} onChange={e=>setShift({...shift,startTime:e.target.value})}/><input type="time" className="border rounded p-2 flex-1" value={shift.endTime} onChange={e=>setShift({...shift,endTime:e.target.value})}/></div><button className="bg-slate-900 text-white rounded p-2 font-bold" onClick={()=>saveShift().catch(e=>setMessage(e.message))}>Lưu ca làm</button></div><div className="mt-3 text-xs text-slate-500">Đã phân {shifts.length} ca.</div></div></section>
    {(role==='CEO'||role==='Accountant')&&<section className="bg-white border rounded-2xl p-5"><h2 className="font-black">Khóa kỳ công và bảng lương • {currentPeriod}</h2><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>lockPeriod(!period?.attendance_locked,Boolean(period?.payroll_locked))} className="border rounded-lg px-4 py-2 font-bold">{period?.attendance_locked?'Mở bảng công':'Khóa bảng công'}</button><button onClick={()=>lockPeriod(Boolean(period?.attendance_locked),!period?.payroll_locked)} className="border rounded-lg px-4 py-2 font-bold">{period?.payroll_locked?'Mở bảng lương':'Khóa bảng lương'}</button></div></section>}
    <section className="bg-white border rounded-2xl p-5"><h2 className="font-black mb-3">Cấu hình geofence công trường</h2><div className="grid md:grid-cols-2 gap-3">{projects.map(p=><div key={p.id} className="border rounded-xl p-3"><div className="font-bold">{p.name}</div><div className="grid grid-cols-3 gap-1 mt-2"><input className="border rounded p-1" placeholder="Vĩ độ" value={p.latitude||''} onChange={e=>setProjects(rows=>rows.map(x=>x.id===p.id?{...x,latitude:Number(e.target.value)}:x))}/><input className="border rounded p-1" placeholder="Kinh độ" value={p.longitude||''} onChange={e=>setProjects(rows=>rows.map(x=>x.id===p.id?{...x,longitude:Number(e.target.value)}:x))}/><input className="border rounded p-1" placeholder="Bán kính m" value={p.geofenceRadius||''} onChange={e=>setProjects(rows=>rows.map(x=>x.id===p.id?{...x,geofenceRadius:Number(e.target.value)}:x))}/></div></div>)}</div></section>
  </div>;
}
